### PR TITLE
Add testing on Python 3.9

### PR DESCRIPTION
**Pull request by MichaelClerx**
See #330

Updated testing via github actions:

- Added windows and os/x tests, using latests version of deps matching requirements
- Added ubuntu only testing using pinned requirements
- Split coverage and style testing off into their own actions
- Removed appveyor testing config

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Have updated pinned deps using `pip-compile` within a Python 3.5 virtualenv, so they won't be too new to be available there.

Now getting this error on 3.8, with the pinned deps (but why only on 3.8?)

```
=================================== FAILURES ===================================
_______________ TestUnitConversion.test_complex_conversion_rule ________________

self = <tests.test_unit_conversion.TestUnitConversion object at 0x7f8aee70ccd0>
br_model = <cellmlmanip.model.Model object at 0x7f8aee0243a0>

    def test_complex_conversion_rule(self, br_model):
        """
        Tests adding a complex conversion rule for incompatible units works as expected.
        """
        uA_per_mm2 = br_model.units.get_unit('uA_per_mm2')
        uA_per_uF = br_model.units.add_unit('uA_per_uF', 'ampere / 1e6 / (farad * 1e-6)')
    
        # Get and check amplitude
        amplitude = br_model.get_variable_by_ontology_term((shared.OXMETA, "membrane_stimulus_current_amplitude"))
        assert str(amplitude) == 'stimulus_protocol$IstimAmplitude'
        assert amplitude.units == uA_per_mm2
        eqs = br_model.get_equations_for([amplitude])
        assert str(eqs) == '[Eq(_stimulus_protocol$IstimAmplitude, 0.5)]'
    
        # Add conversion rule from uA_per_mm2 to uA_per_uF
        chaste_membrane_capacitance = br_model.units.Quantity(
            sympy.Function('HeartConfig::Instance()->GetCapacitance', real=True)(),
            uA_per_uF / uA_per_mm2)
    
        # Add complex rule
dst_ = <UnitsContainer({'[length]': 2.0})>

    def enable_contexts(self, *names_or_contexts, **kwargs):
        """Enable contexts provided by name or by object.
    
        :param names_or_contexts: sequence of the contexts or contexts names/alias
        :param kwargs: keyword arguments for the context
        """
    
        # If present, copy the defaults from the containing contexts
        if self._active_ctx.defaults:
            kwargs = dict(self._active_ctx.defaults, **kwargs)
    
        # For each name, we first find the corresponding context
        ctxs = list((self._contexts[name] if isinstance(name, string_types) else name)
                    for name in names_or_contexts)
    
        # Check if the contexts have been checked first, if not we make sure
        # that dimensions are expressed in terms of base dimensions.
        for ctx in ctxs:
            if getattr(ctx, '_checked', False):
                continue
>           for (src, dst), func in ctx.funcs.items():
E           RuntimeError: dictionary keys changed during iteration

/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/pint/registry.py:1108: RuntimeError
=========================== short test summary info ============================
FAILED tests/test_unit_conversion.py::TestUnitConversion::test_complex_conversion_rule
FAILED tests/test_unit_conversion.py::TestUnitConversion::test_complex_conversion_rule_with_factor
FAILED tests/test_unit_conversion.py::TestUnitConversion::test_complex_conversion_rules_combined
======================== 3 failed, 207 passed in 7.61s =========================
Error: Process completed with exit code 1.
```

**Comment by MichaelClerx** [comment]
OK, the pinned versions are now _only_ used in a test on Python 3.6.

**Comment by MauriceHendrix** [comment]
I'm a bit surprised to see code coverage decreased?

**Comment by MichaelClerx** [comment]
Me too!

> elif isinstance(cf, sympy.Mul) and 1.0 in cf.args:
>  # We get an ugly artefact whereby pint gives us a 1.0*cf as conversion factor; remove the 1.0
>  return sympy.Mul(*[a for a in cf.args if a != 1.0])

Maybe newer pint doesn't do that anymore?

**Comment by MauriceHendrix** [comment]
> Me too!
> 
> It's these lines:
> 
> ```
>  elif isinstance(cf, sympy.Mul) and 1.0 in cf.args:
>   # We get an ugly artefact whereby pint gives us a 1.0*cf as conversion factor; remove the 1.0
>   return sympy.Mul(*[a for a in cf.args if a != 1.0])
> ```
> 
> Maybe newer pint doesn't do that anymore?

aah yes that's quite possible

**Comment by MichaelClerx** [comment]
Ah. Yes. I do get 100% coverage with pint 0.9. So will add a pragma for that line then!

**Comment by MichaelClerx** [comment]
Fixed now @MauriceHendrix !

**Review by MauriceHendrix — APPROVED** [review]

**Pull request merged**
