### PR TITLE
Support for secondary trig functions

### PR DESCRIPTION
**Pull request by MichaelClerx**
## Description
Cellmlmanip had partial support for secondary trig functions (sec, csc, cot, and their inverse and hyperbolic functions). This PR adds tests for the cellml-to-sympy transpiler and adds methods to the printer to write expressions to evaluate them (using python's `math` module, which doesn't have these expressions natively)

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Documentation checklist
- [x] I have updated all documentation in the code where necessary.
- [x] I have checked spelling in all (new) comments and documentation.
- [x] I have added a note to RELEASE.md if relevant (new feature, breaking change, or notable bug fix).

## Testing
- [x] Testing is done automatically and codecov shows test coverage

### CODE REVIEW

**Review by MauriceHendrix — APPROVED** [review]
I checked and it doesn't seem to interfere with chaste_codegen (doesn't change test results). 

Adding this to the chaste printer also doesn't add the test results, which would perhaps suggest that these don't appear in the test cellml files ( I didn't check that)

**Comment by MichaelClerx** [comment]
Yeah I'd be very surprised if any of these show up in cardiac cell models. I can think of one with a `tanh` function, and one with an `acos`, but that's pretty much it as far as trig functions are concerned

**Comment by MichaelClerx** [comment]
They are part of CellML though (for the stupidest reason: "it was easy to implement in C". I tried to reduce the number of trig functions a bit for CellML 2 but nobody else wanted too)

**Comment by MauriceHendrix** [comment]
ok fair enough, so we should probably have them in chaste_codegen

**Pull request merged**
