### PR TITLE
Set up sphinx documentation

### PR DESCRIPTION
**Pull request by MichaelClerx**
First files to allow documentation to be built. Part of #93

### CODE REVIEW

**Comment by MichaelClerx** [comment]
We can use readthedocs.io for that, but would make more sense to wait until we have some users I guess

**Comment by jonc125** [comment]
I think you can do it without having to publish on PyPI though, right? And it'll be useful for us to read even if no-one else looks at it!

**Comment by MichaelClerx** [comment]
Yeah you can hook it up to a repo, but I don't really want to add more stuff to my personal account!

**Comment by jonc125** [comment]
I'll do it on mine next week some time then :)

**Comment by MichaelClerx** [comment]
Thanks!

**Pull request merged**
