### PR TITLE
get_symbol_by_cmeta_id bug

### LINKED ISSUE #156: Possible bug in get_symbol_by_cmeta_id
Again using my very basic model:

    <component name="env_ode">
        
        <variable name="time" public_interface="in" units="ms"/>
        <variable cmeta:id="sv11" initial_value="2" name="sv1" units="mV"/>
        <math xmlns="http://www.w3.org/1998/Math/MathML">
            <apply>
                <eq/>
                <apply>
                    <diff/>
                    <bvar>
                        <ci>time</ci>
                    </bvar>
                    <ci>sv1</ci>
                </apply>
                <cn cellml:units="mV_per_ms">1</cn>
            </apply>
        </math>
    </component>

no node is every created for the variable sv1 and so get_symbol_by_cmeta_id('sv11')  does not find the variable.

The model is so simple it does not ever occur as lhs of anything but it would be the variable that was the output of simulating this toy model.

Bug or not ??

### PR DESCRIPTION
**Pull request by skeating**
Fixes #156

### CODE REVIEW

**Comment by MichaelClerx** [comment]
@MauriceHendrix what do you think? I guess you never use the graph directly, so the state variables being in it won't bother you either?

**Comment by MichaelClerx** [comment]
We could also consider sticking the initial value in as the equation, I guess?

**Comment by jonc125** [comment]
> We could also consider sticking the initial value in as the equation, I guess?

Don't do this, it'll lead to an over-constrained model!

**Comment by MauriceHendrix** [comment]
> > We could also consider sticking the initial value in as the equation, I guess?
> 
> Don't do this, it'll lead to an over-constrained model!
> 
> While as suggested elsewhere adding equations for constants makes sense, we do need to keep the initial_value concept for state variables.

I would then need to filter out these initial values as they're treated differently in the output, not impossible, but the way it is it's quite convenient.

**Comment by jonc125** [comment]
> > > We could also consider sticking the initial value in as the equation, I guess?
> > 
> > 
> > Don't do this, it'll lead to an over-constrained model!
> > While as suggested elsewhere adding equations for constants makes sense, we do need to keep the initial_value concept for state variables.
> 
> I would then need to filter out these initial values as they're treated differently in the output, not impossible, but the way it is it's quite convenient.

Which initial values do you mean? See also #135, particularly the last comment.

**Pull request merged**
