### PR TITLE
243 transform units bug

### LINKED ISSUE #243: Transform constants doesn't add units
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- CellML Test Suite. https://github.com/MichaelClerx/cellml-validation -->
<!-- CellML 1.0, 3.4.6.4: Siblings are connected via the public interface -->
<!-- B.a to C.a, both children of A -->
<model name="map_variables_nested_sibling_connection"
       xmlns="http://www.cellml.org/cellml/1.0#">
  <component name="A" />
  <component name="B">
    <variable name="a" units="newton" public_interface="out" initial_value="1" />
  </component>
  <component name="C">
    <variable name="a" units="newton" public_interface="in" />
  </component>
  <group>
    <relationship_ref relationship="encapsulation" />
    <component_ref component="A">
      <component_ref component="B" />
      <component_ref component="C" />
    </component_ref>
  </group>
  <connection>
    <map_components component_1="B" component_2="C" />
    <map_variables variable_1="a" variable_2="a" />
  </connection>
</model>
```

gives the error

```
Units newton 1.0 kilogram * meter / second ** 2 != dimensionless 1 dimensionless
```

Not sure what's happening here. Accidental unit conversion?

### PR DESCRIPTION
**Pull request by MichaelClerx**
Fixes #243 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Testing
- [X] Testing is done automatically and codecov shows test coverage

### CODE REVIEW

**Comment by MichaelClerx** [comment]
Weirdly, I now see a new error from `TestModelFunctions.test_get_derived_quantities`

```
Message: 'The source variable has not been assigned a value yet'
Arguments: ('circle_sibling$y', 'circle_parent$y')
--------------------------------- Captured log setup ----------------------------------
INFO     cellmlmanip.model:model.py:293 Connection req. unit conversion: Eq(_time_units_conversion1$time, _0.001*_environment$time)
INFO     cellmlmanip.model:model.py:293 Connection req. unit conversion: Eq(_time_units_conversion2$time, _1000.0*_environment$time)
```

**Comment by jonc125** [comment]
> Weirdly, I now see a new error from `TestModelFunctions.test_get_derived_quantities`

I think that's because you got rid of some %s tokens in the logging in an earlier PR #237 !
`logger.info('The source variable has not been assigned a value yet', target.name, source.name)`

**Comment by MichaelClerx** [comment]
Oh dear!

**Comment by MichaelClerx** [comment]
> I think that's because you got rid of some %s tokens in the logging in an earlier PR #237 !
logger.info('The source variable has not been assigned a value yet', target.name, source.name)

I think I must have accidentally hit the keyboard shortcut for deleting a line :flushed:

**Comment by jonc125** [comment]
Though I think the failing test must be because the change to `transform_constants` means the LHS no longer gets marked as a parameter in the graph, presumably because `equation.rhs.is_number` is False. Do we need to tweak `NumberDummy` so it claims to be a number to Sympy?

**Comment by MichaelClerx** [comment]
We're not meant to have any numbers at that point though, so perhaps it should be an `isinstance(NumberDummy)` instead?

**Comment by MichaelClerx** [comment]
(Also worried having sympy treat our number dummies as numbers would bring back problems we're avoiding by having them _not_ being numbers)

**Comment by MichaelClerx** [comment]
Seems to me the current test is wrong!

It shows `single_ode_rhs_computed_var$a = -1.0` should be marked as a derived quantity.

Paging @MauriceHendrix just in case that was intended behaviour

**Pull request merged**
