### PR TITLE
Bump required PINT version to 0.16.0

### PR DESCRIPTION
**Pull request by MichaelClerx**
See https://github.com/ModellingWebLab/weblab-fc/issues/221

### CODE REVIEW

**Comment by MauriceHendrix** [comment]
odd that this decreases test coverage

**Review by MauriceHendrix — APPROVED** [review]
odd that this decreases test coverage

**Comment by MauriceHendrix** [comment]
hhm @MichaelClerx  actually I just noticed with the requirement Pint>=0.16 on python3.5 it still installs Pint 0.9 anyway as that's the latest compatible version. It doesn't stop my tests from passing, but it might be an issue for yours.

**Comment by MichaelClerx** [comment]
> hhm @MichaelClerx actually I just noticed with the requirement Pint>=0.16 on python3.5 it still installs Pint 0.9 anyway as that's the latest compatible version. It doesn't stop my tests from passing, but it might be an issue for yours.

Good find!
I think that was the pinned dependencies that Jonathan likes using. I've updated those to pint 0.16.0 too now, not sure if I've done that right 😅

**Comment by MauriceHendrix** [comment]
I think Pint 0.16 just isn't compatible with Python 3.5

```
Could not find a version that satisfies the requirement pint>=0.16.0 (from cellmlmanip==0.2.0) (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.2, 0.2.1, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.4, 0.4.1, 0.4.2, 0.5, 0.5.1, 0.5.2, 0.6, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.9)
```

**Comment by MichaelClerx** [comment]
In that case we might need to drop 3.5 support? If `pint` is no longer supporting it... @jonc125 ?

**Comment by MichaelClerx** [comment]
Or we can just keep testing with 0.9 I guess, if we need 3.5 for chaste?

**Comment by MauriceHendrix** [comment]
> Or we can just keep testing with 0.9 I guess, if we need 3.5 for chaste?

I would be slightly reluctant to pull python 3.5 at this stage, it's only 1 version below what e run on our server at Nottingham so not hard to imagine somebody else still running it on theirs.

**Comment by MichaelClerx** [comment]
OK, it works with 0.9 as minimum required so let's just merge with that then?

**Pull request merged**
