### PR TITLE
Made cellmlmanip more christmassy.

### PR DESCRIPTION
**Pull request by MichaelClerx**
## Description
Makes cellmlmanip more christmassy.

## Motivation and Context
Cellmlmanip was not very christmassy

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] I have updated all documentation necessary.
- [x] I have checked spelling in (new) comments.

## Testing
- [X] Testing is done automatically and codecov shows test coverage
- [ ] This cannot be tested automatically

### CODE REVIEW

**Comment by MauriceHendrix** [comment]
Ha ha ha ha ha that was a good laugh

**Comment by jonc125** [comment]
Do any of our existing models work for elves? I think we need some data that we can compare simulations against in the Web Lab!

**Comment by MauriceHendrix** [comment]
> Do any of our existing models work for elves? I think we need some data that we can compare simulations against in the Web Lab!

we need to make sure the data is wrapped up with nice wrapping paper!

**Comment by skeating** [comment]
We need to model santas work rate

**Pull request closed without merging**
