### PR TITLE
Set up appveyor testing

### PR DESCRIPTION
**Pull request by MichaelClerx**
See #55

### CODE REVIEW

**Comment by MichaelClerx** [comment]
@tamuri no idea what's happening here! Very weird error message. @MauriceHendrix do you see the same if you test cellmlmanip on windows?

**Comment by MichaelClerx** [comment]
```
        # Annotation with a cmeta id that doesn't exist
        with pytest.raises(KeyError) as e:
            model.get_symbol_by_ontology_term(oxmeta, 'membrane_potential')
>       assert 'No variable with cmeta id' in str(e)
E       AssertionError: assert 'No variable with cmeta id' in '<ExceptionInfo KeyError tblen=4>'
E        +  where '<ExceptionInfo KeyError tblen=4>' = str(<ExceptionInfo KeyError tblen=4>)
tests\test_rdf.py:58: AssertionError
```

**Comment by MichaelClerx** [comment]
Think I found it

**Comment by MauriceHendrix** [comment]
It could be my build but lxml==4.2.2 gives an error
The version currently used on weblab-cg is perfecly fine.
This is while using venv rather than conda.

**Pull request merged**
