### PR TITLE
I think we should consider adding a pull request template

### PR DESCRIPTION
**Pull request by MauriceHendrix**
## Description

I'm suggesting a pull request template. Please feel free to discuss the template itself I just copied it from [some website](https://www.talater.com/open-source-templates/#/page/99) and I'm sure there are better ones.

## Motivation and Context

I'm getting a lot of 'what is this why do we need this' type comments on my PRs which is pretty frustrating. I'm hoping having this template will serve as a reminder to add a better description, and will hopefully reduce this frustration. See for more #164 

## How Has This Been Tested?

I've tested it on a private github repository and it seems to work as intended. Please note: There is no actual code being changed in this PR

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by MichaelClerx** [comment]
In other projects I'm involved in we've avoided a lot of confusion/frustration by using the following procedure for every bug, new feature, or other non-trivial code change (anything bigger than changing a docstring / fixing a typo):

1. Create an issue stating the problem and proposed solution, or introducing the feature you want to add.
2. Discuss in the issue thread, for really big things maybe sketch a solution, work out method and class names etc. Discuss how these changes will affect other parts of the code.
3. Once a vague idea / direction is accepted, code up a solution and add a PR

We've not been sticking to this 100% because something explaining something is harder than just showing the code, but there have been several cases where a discussion in an issue thread helped me avoid wasted effort. For example when others pointed out some new functionality I was thinking of could already be achieved a different way. Or when I suggested new methods that seemed obvious to me but confused everybody else, so we ended up calling them something else / solving the issue in a different part of the code.

One way of thinking about it might be that the issue discussion is the "design" step, and the PR discussion is the "implementation" step.

Happy to discuss other ways of doing it of course!

**Comment by MichaelClerx** [comment]
Here's a really long [CONTRIBUTING.md](https://github.com/pints-team/pints/blob/master/CONTRIBUTING.md) that I wrote for PINTS (fitting software) just to formalise the workflow we were using and to serve as a reference for ourselves, students, & other newcomers. Again, this is just one way of doing it, happy to learn & to discuss!

**Comment by MauriceHendrix** [comment]
> In other projects I'm involved in we've avoided a lot of confusion/frustration by using the following procedure for every bug, new feature, or other non-trivial code change (anything bigger than changing a docstring / fixing a typo):
> 
> 1. Create an issue stating the problem and proposed solution, or introducing the feature you want to add.
> 2. Discuss the proposal on the issue page. For really big things maybe sketch a solution, and agree on method and class names. Discuss how these changes will affect other parts of the code.
> 3. Once a vague idea / direction is accepted, code up a solution and add a PR
> 
> We've not been sticking to this 100% because sometimes explaining something is harder than just showing the code, but there have been several cases where a discussion in an issue thread helped me avoid wasted effort. For example when others pointed out that some new functionality I was thinking of could already be achieved a different way. Or when I suggested new methods that seemed obvious to me but confused everybody else, so we ended up calling them something else / solving the issue in a different part of the code.
> 
> One way of thinking about it might be that the issue discussion is the "design" step, and the PR discussion is the "implementation" step.
> 
> Happy to discuss other ways of doing it of course!

Sounds good on paper, but the way it is currently I'm starting to feel very put off of contributing, especially where I can just put a work-around in chatse_cg as trying to get something accepted is just not worth the pain!

My main frustrations have been so far:
- I get most of my PRs immediately shot down, even (or especially) after they've been discussed on slack. I do recognize we probably need to provide better info (hence the pull request template), but I would really appreciate a more supportive environment!

- I see a lot of tinny comments like typos, style/syntax comments leading to a change request that then ages to get re-approved. What a colossal waste of everybody's time! 
In my view if you agree with the concept another round of reviews should not be necessary, so this should lead to an approve, but with comments. If we can't trust each other to do the little fixes needed we've got bigger problems in my opinion.
By the way typos can be easily corrected via the web interface. I don't know what people think but I would prefer reviewers to just make the change. (For the record I do agree typos are important).

- When reviewing a PR that fixes something in pre-existing code code can we please try to keep it focused on that change? Of course is there is a genuinely better way of doing things sure, but I've been dragged into justifying and explaining code that was there already or refactoring substantial bits just to get a tiny fix accepted. I know I should probably be more assertive in saying 'not for this PR'.

**Comment by MauriceHendrix** [comment]
> Here's a really long [CONTRIBUTING.md](https://github.com/pints-team/pints/blob/master/CONTRIBUTING.md) that I wrote for PINTS (fitting software) just to formalise the workflow we were using and to serve as a reference for ourselves, students, & other newcomers. Again, this is just one way of doing it, happy to learn & to discuss!

:scream:

**Comment by jonc125** [comment]
I think this template is fine, so happy to merge. The discussion has moved on to the bigger picture, which might be better in #164 :). So I'll talk about that there!

**Pull request merged**
